### ISSUE TITLE
 Failed to rename a file in writing.py

### ISSUE THREAD

**Issue by take0212** [pfnet/pytorch-pfn-extras#11]
The following error happens.

![image](https://user-images.githubusercontent.com/43694878/82112669-0ac22c80-978a-11ea-8cd6-55ee7b83691b.png)

![image](https://user-images.githubusercontent.com/43694878/82112676-27f6fb00-978a-11ea-8e99-cae7fe6caa79.png)

I fixed it.

![image](https://user-images.githubusercontent.com/43694878/82112652-bf0f8300-9789-11ea-9301-445881ecb682.png)

**Comment by kmaehashi** [comment]
Thanks for reporting! This will be fixed in the next release.
