### ISSUE TITLE
Create internal debug tools

### ISSUE THREAD

**Issue by emcastillo** [pfnet/pytorch-pfn-extras#172]
We need some kind of logging mechanism for debug

When loading snapshots or verifying trigger checks having a 
`PPE_LOG_LEVEL` environment variable that allows us to obtain DEBUG information 
(snapshot not found, snapshot invalid, etc.) will be very useful.

**Comment by kmaehashi** [comment]
We can use `logging` module and switch the log level (e.g. `ERROR` by default, `DEBUG` if PPE_LOG_LEVEL is set)
