### ISSUE TITLE
The new ppe profiler introduces an unexpected ill-effect where users cannot set multiprocessing process start mode after importing ppe

### ISSUE THREAD

**Issue by belltailjp** [pfnet/pytorch-pfn-extras#238]
I found out that importing the latest ppe will cause 

```python
>>> import multiprocessing as mp
>>> import pytorch_pfn_extras as ppe
>>> print(ppe.__version__)
>>> mp.set_start_method('forkserver')   # 'fork' or whatever

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/xxxx/.local/lib/python3.8/site-packages/pytorch_pfn_extras/__init__.py", line 10, in <module>
    from pytorch_pfn_extras import profiler  # NOQA
  File "/home/xxxx/.local/lib/python3.8/site-packages/pytorch_pfn_extras/profiler/__init__.py", line 1, in <module>
    from pytorch_pfn_extras.profiler._record import record  # NOQA
  File "/home/xxxx/.local/lib/python3.8/site-packages/pytorch_pfn_extras/profiler/_record.py", line 4, in <module>
    from pytorch_pfn_extras.profiler._time_summary import time_summary
  File "/home/xxxx/.local/lib/python3.8/site-packages/pytorch_pfn_extras/profiler/_time_summary.py", line 157, in <module>
    mp.set_start_method('forkserver')
  File "/usr/local/lib/python3.8/multiprocessing/context.py", line 243, in set_start_method
    raise RuntimeError('context has already been set')
RuntimeError: context has already been set
```

What is actually happening inside is very similar to this. 
https://github.com/numba/numba/pull/5724
Only the difference between ppe is that ppe creates `multiprocessing.JoinableQueue` instead of `get_context()` as in numba. In either case the process start method is implicitly fixed to "fork" right then and we can no longer change it anymore during the process lifetime, no matter which mode actually we want.

This happens at **import time** of ppe, specifically in instantiation of `TimeSummary`, not when the first time actually use it.
https://github.com/pfnet/pytorch-pfn-extras/blob/94a0d5092731ca94cc2deefaf5a55d037ec30dcc/pytorch_pfn_extras/profiler/_time_summary.py#L155
https://github.com/pfnet/pytorch-pfn-extras/blob/94a0d5092731ca94cc2deefaf5a55d037ec30dcc/pytorch_pfn_extras/profiler/_time_summary.py#L18

### Simple workaround

As written in https://github.com/numba/numba/pull/5724, if we set start method before importing ppe, it works fine.

```python
>>> import multiprocessing as mp
>>> mp.set_start_method('forkserver')
>>> import pytorch_pfn_extras as ppe
>>> print(ppe.__version__)
```

### Fundamental fix

I think we need to delay instantiation of _CPUWorker (or at least creation of `JoinableQueue`) to when it actually becomes necessary.

**Comment by emcastillo** [comment]
UGh, this is an ugly one, sorry for the problem and thanks for the debugging

**Comment by belltailjp** [comment]
I initially thought it's gonna be a little tough to solve, but soon have came up with an idea to just simply delay instantiation of `JoinableQueue`, which I attempted in #240 .
But I'm actually unaware that when the lazy open will happen, since I couldn't find how to use the profiling mechanism.

Maybe.. I'm afraid `_CPUWorker.__init__` will immediately start `self._worker` in a background thread so this fix won't solve the issue, will it?

**Comment by emcastillo** [comment]
Right, we need to delay creation of both workers too :(
