### ISSUE TITLE
Trainer: Add an option to enable profiling in Handler config

### ISSUE THREAD

**Issue by kmaehashi** [pfnet/pytorch-pfn-extras#358]
Add an option to automatically wrap training loop with with `torch.cuda.profiler.profile()` and `torch.autograd.profiler.emit_nvtx()` (when CUDA is enabled).

**Comment by kmaehashi** [comment]
* To support benchmarking the whole training process including data loader etc., it is better to have support for benchmarking in Trainer.
* Different mechanisms may be needed for each runtime / device backend. My idea is to have a new API in Runtime (e.g., `with runtime.profile_context()`) that returns a context object to profile the scope, based on the config passed to Runtime.

**Comment by emcastillo** [comment]
How about adding this in https://github.com/pfnet/pytorch-pfn-extras/blob/master/pytorch_pfn_extras/profiler/_record.py
class, currently is all wrapped with this in trainer/evaluator so we get it for free

**Comment by kmaehashi** [comment]
PyTorch 1.8 introduced `torch.profiler` and that can be a replacement for `pytorch_pfn_extras.profiler`?
