### ISSUE TITLE
Displaying logs and progress bars in Jupyter

### ISSUE THREAD

**Issue by emcastillo** [pfnet/pytorch-pfn-extras#37]
They don't work ok.

TBE

**Comment by kmaehashi** [comment]
Maybe we need to use `google.colab.output.clear`? https://colab.research.google.com/notebooks/snippets/advanced_outputs.ipynb#scrollTo=BPyFjT1ImHRQ

**Comment by emcastillo** [comment]
Probably, I will do some tests with it ...

**Comment by kmaehashi** [comment]
Maybe `from IPython.display import clear_output`?

**Comment by emcastillo** [comment]
We now support extensions explictily for Jupyter, use these instead.
