### ISSUE TITLE
DistributedSnapshot with NCCL

### ISSUE THREAD

**Issue by raven38** [pfnet/pytorch-pfn-extras#53]
I want to use DistributedSnapshot with NCCL. However, current `_get_ranks_from_env` only accept environment variables for MPI and MV1. 
In pytorch documentation, they use the environment variables: `WORLD_SIZE`, `RANK`, and `LOCAL_RANK`, for specifying a process.

https://github.com/pfnet/pytorch-pfn-extras/blob/8b16df9433a024c63d786c76f1e7ccbb88847283/pytorch_pfn_extras/training/extensions/_snapshot.py#L473-L488

**Comment by emcastillo** [comment]
Hi, thanks for the feedback, this is because use to run our training directly with mpirun so we rely in these variables.
I agree this is not correct and I am going to fix it now.

**Comment by emcastillo** [comment]
I just sent a fix for this in #58
I hope this will fix it 😇
