### ISSUE TITLE
Support passing `closure` argument to optimizers

### ISSUE THREAD

**Issue by kmaehashi** [pfnet/pytorch-pfn-extras#636]
Optimizers supports two kind of `step()` call:

https://pytorch.org/docs/stable/optim.html#taking-an-optimization-step

However, some optimizers require mandatory `closure` argument:

https://pytorch.org/docs/stable/generated/torch.optim.LBFGS.html#torch.optim.LBFGS

Currently, ExtensionsManager and Logic do not support these optimizers.

**Comment by linshoK** [comment]
Since `torch.cuda.amp.GradScaler` does not support the step method by closuer, it must be processed by branching.

https://pytorch.org/docs/stable/amp.html#torch.cuda.amp.GradScaler.step

**Comment by linshoK** [comment]
The `torch.optim.obfgs.LBFGS` class, which requires a clousure, assumes that the clousure returns an object that can be converted to a float.

https://pytorch.org/docs/stable/_modules/torch/optim/lbfgs.html#LBFGS.step
