### ISSUE TITLE
Fix nightly CPU test failures

### ISSUE THREAD

**Issue by kmaehashi** [pfnet/pytorch-pfn-extras#784]
https://github.com/pfnet/pytorch-pfn-extras/actions/workflows/nightly-test-cpu.yml

**Comment by take-cheeze** [comment]
Latest summary https://github.com/pfnet/pytorch-pfn-extras/actions/runs/6764593441/job/18383088613#step:5:366
```
=========================== short test summary info ============================
FAILED tests/pytorch_pfn_extras_tests/distributed_tests/test_distributed_validation_sampler.py::test_no_distributed_available - ValueError: Default process group has not been initialized, please make sure to call init_process_group.
FAILED tests/pytorch_pfn_extras_tests/training_tests/test_manager.py::test_ignite_extensions_manager_state_dict - UserWarning: PairwiseParallel is deprecated and will be removed soon. Use ColwiseParallel and RowwiseParallel instead.
FAILED tests/pytorch_pfn_extras_tests/training_tests/extensions_tests/test_evaluator.py::test_ignite_evaluator_reporting_metrics - UserWarning: PairwiseParallel is deprecated and will be removed soon. Use ColwiseParallel and RowwiseParallel instead.
FAILED tests/pytorch_pfn_extras_tests/training_tests/extensions_tests/test_progress_bar_notebook.py::test_ignite_extensions_manager_with_progressbar_notebook - UserWarning: PairwiseParallel is deprecated and will be removed soon. Use ColwiseParallel and RowwiseParallel instead.
```

**Comment by linshokaku** [comment]
@emcastillo 
https://github.com/pfnet/pytorch-pfn-extras/blob/dd8ed077d17b27f5828a53cbf2156a408ecdcec8/tests/pytorch_pfn_extras_tests/distributed_tests/test_distributed_validation_sampler.py#L81-L85
The first error among the errors that are appearing is related to the content added in this PR.
https://github.com/pfnet/pytorch-pfn-extras/pull/551

The reason this unit test is failing is that despite the title of the test, `torch.distributed.is_available()` returns `True`, so the exception is not raised as expected. This test already does not behave as it is named.

`torch.distributed.is_available()` is a function to determine if the torch.distributed module is available, and is separate from `torch.distributed.is_initialized()`, which checks to see if the distributed communication has been initialized. `torch.distributed.is_initialized()`, which is supposed to be `True` in most cases.
Is it possible to remove this test in some cases?
