### ISSUE TITLE
Can we use classmethod or staticmethod directry from type?

### ISSUE THREAD

**Issue by kondounagi** [pfnet/pytorch-pfn-extras#826]
I would like to call staticmethod or classmethod like this.
```
hoge:
  type: HogeClass.classmethod # HogeClass.classmethod not in types 
```
How is it possible?
Or, is there any recommended way to do an equivalent thing?

**Comment by kmaehashi** [comment]
All `type`s must be declared in `types` dict.

**Comment by kondounagi** [comment]
I understood it.Sorry for silly question.This library is really helpful for us.Thanks2024/07/31 20:15、Kenichi Maehashi ***@***.***>のメール:﻿
All types must be declared in types dict.
